[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "malwaresandbox"
version = "1.0.0"
description = "A simple automated malware analysis sandbox for Windows"
authors = [
    { name="Scofield", email="scofieldtosan.lori@hmail.com" }
]
dependencies = [
    "psutil"
]

[project.scripts]
malwaresandbox = "malwaresandbox.main:main"
